# Generated by Django 5.0.14 on 2026-09-28 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_branch',
            field=models.ForeignKey(blank=True, help_text='Required for STAFF_ADMIN/TRAINER/MEMBER. Null for OWNER (owners implicitly have all branches in their organization).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Required for every business user. Null is reserved for platform-level Django superusers only (not a product role).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='accounts_us_organiz_f36d76_idx'),
        ),
    ]
