# Generated by Django 5.0.14 on 2026-09-28 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0002_organizationsettings_min_checkin_interval_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('event_type', models.CharField(choices=[('MEMBERSHIP_CREATED', 'Membership created'), ('PAYMENT_SUCCESSFUL', 'Payment successful'), ('PAYMENT_FAILED', 'Payment failed'), ('MEMBERSHIP_EXPIRING', 'Membership expiring'), ('MEMBERSHIP_EXPIRED', 'Membership expired'), ('CLASS_BOOKING', 'Class booking'), ('CLASS_REMINDER', 'Class reminder'), ('PT_BOOKING', 'PT booking'), ('PT_REMINDER', 'PT reminder'), ('BIRTHDAY', 'Birthday'), ('FREEZE_APPROVED', 'Freeze approved')], max_length=32)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-app')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('recipient_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='members.member')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event_type'], name='notificatio_organiz_c7557b_idx'), models.Index(fields=['organization', 'recipient_member'], name='notificatio_organiz_51c62f_idx'), models.Index(fields=['organization', 'recipient_user'], name='notificatio_organiz_f2cbaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('event_type', models.CharField(choices=[('MEMBERSHIP_CREATED', 'Membership created'), ('PAYMENT_SUCCESSFUL', 'Payment successful'), ('PAYMENT_FAILED', 'Payment failed'), ('MEMBERSHIP_EXPIRING', 'Membership expiring'), ('MEMBERSHIP_EXPIRED', 'Membership expired'), ('CLASS_BOOKING', 'Class booking'), ('CLASS_REMINDER', 'Class reminder'), ('PT_BOOKING', 'PT booking'), ('PT_REMINDER', 'PT reminder'), ('BIRTHDAY', 'Birthday'), ('FREEZE_APPROVED', 'Freeze approved')], max_length=32)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-app')], max_length=16)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['event_type', 'channel'],
                'indexes': [models.Index(fields=['organization', 'event_type', 'channel'], name='notificatio_organiz_e80f2c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'event_type', 'channel'), name='unique_notification_template_per_org_event_channel'),
        ),
    ]
