# Generated by Django 5.0.14 on 2026-09-28 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('gstin', models.CharField(blank=True, help_text='GST identification number, if registered.', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('default_timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('freeze_policy', models.CharField(choices=[('EXTEND_BY_FREEZE_DAYS', 'Extend end date by frozen days'), ('PAUSE_NO_EXTEND', 'Pause membership, no automatic extension')], default='EXTEND_BY_FREEZE_DAYS', help_text='Default policy is a placeholder pending OQ-005 confirmation.', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_number_next_sequence', models.PositiveIntegerField(default=1)),
                ('notification_defaults', models.JSONField(blank=True, default=dict)),
                ('billing_defaults', models.JSONField(blank=True, default=dict)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
        ),
    ]
