# Generated by Django 5.0.14 on 2026-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='min_checkin_interval_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Provisional duplicate-check-in window (minutes). Product rule still open.'),
        ),
    ]
