# Generated by Django 5.0.14 on 2026-09-28 09:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_organizationsettings_min_checkin_interval_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).",
                        unique=True,
                    ),
                ),
                ("specializations", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                (
                    "compensation_model",
                    models.CharField(
                        choices=[
                            ("FIXED_SALARY", "Fixed salary"),
                            ("PER_SESSION", "Per session"),
                            ("PER_CLASS", "Per class"),
                            ("REVENUE_SHARE", "Revenue share"),
                        ],
                        default="FIXED_SALARY",
                        max_length=20,
                    ),
                ),
                (
                    "compensation_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trainerprofile",
            index=models.Index(fields=["organization"], name="trainers_tr_organiz_idx"),
        ),
    ]
