# Generated by Django 5.0.14 on 2026-09-28 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('plan_name', models.CharField(max_length=255)),
                ('sessions_purchased', models.PositiveIntegerField()),
                ('sessions_consumed', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_packages', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_sessions', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pt.ptpackage')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ptpackage',
            index=models.Index(fields=['organization', 'member'], name='pt_ptpackag_organiz_96dfc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ptpackage',
            constraint=models.CheckConstraint(check=models.Q(('sessions_consumed__lte', models.F('sessions_purchased'))), name='pt_consumed_lte_purchased'),
        ),
        migrations.AddIndex(
            model_name='ptsession',
            index=models.Index(fields=['trainer', 'scheduled_at'], name='pt_ptsessio_trainer_52424f_idx'),
        ),
        migrations.AddIndex(
            model_name='ptsession',
            index=models.Index(fields=['member', 'scheduled_at'], name='pt_ptsessio_member__ee8d17_idx'),
        ),
    ]
