# Generated by Django 5.0.14 on 2026-09-28 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branchaccess_member_alter_branchaccess_user_and_more'),
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('checkin_at', models.DateTimeField()),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('STAFF_SEARCH', 'Staff search'), ('QR', 'QR code'), ('BIOMETRIC', 'Biometric/RFID'), ('MANUAL_OVERRIDE', 'Manual override')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('override_reason', models.CharField(blank=True, help_text='Required when method=MANUAL_OVERRIDE (AGENTS.md §20.3 auditability).', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='branches.branch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checkin_at'],
                'indexes': [models.Index(fields=['member', 'checkin_at'], name='attendance__member__0e1279_idx'), models.Index(fields=['branch', 'checkin_at'], name='attendance__branch__c93863_idx')],
            },
        ),
    ]
