# Generated by Django 5.0.14 on 2026-09-28 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchaccess',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_access_grants', to='members.member'),
        ),
        migrations.AlterField(
            model_name='branchaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='branchaccess',
            constraint=models.UniqueConstraint(fields=('member', 'branch'), name='unique_member_branch_access'),
        ),
        migrations.AddConstraint(
            model_name='branchaccess',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('member__isnull', True), ('user__isnull', False)), models.Q(('member__isnull', False), ('user__isnull', True)), _connector='OR'), name='branch_access_exactly_one_of_user_or_member'),
        ),
    ]
