# Generated by Django 5.0.14 on 2026-09-28 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0002_organizationsettings_min_checkin_interval_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(blank=True, max_length=100)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('media_url', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('day_index', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('target_sets', models.PositiveIntegerField()),
                ('target_reps', models.PositiveIntegerField()),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rest_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_prescriptions', to='workouts.exercise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_programs', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_programs_as_trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutprogram'),
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('performed_on', models.DateField()),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workouts.exercise')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_logs', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('workout_day_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workouts.workoutdayexercise')),
            ],
            options={
                'ordering': ['-performed_on', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'member'], name='workouts_wo_organiz_9036c7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutprogram',
            index=models.Index(fields=['organization', 'member'], name='workouts_wo_organiz_6b230c_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutday',
            constraint=models.UniqueConstraint(fields=('program', 'day_index'), name='workouts_day_unique_index'),
        ),
    ]
