# Generated by Django 5.0.14 on 2026-09-28 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branchaccess_member_alter_branchaccess_user_and_more'),
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('recurrence_rule', models.JSONField(blank=True, default=dict)),
                ('booking_policy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_classes', to='branches.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gym_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='gym_classes.gymclass')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque external identifier. Use this in API URLs / QR codes — never expose the internal integer primary key (DEC-012).', unique=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No-show')], default='BOOKED', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_bookings', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='gym_classes.classoccurrence')),
            ],
            options={
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['occurrence', 'status'], name='gym_classes_occurre_f0da40_idx'), models.Index(fields=['member', 'status'], name='gym_classes_member__bcb908_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gymclass',
            index=models.Index(fields=['organization', 'status'], name='gym_classes_organiz_81074e_idx'),
        ),
        migrations.AddConstraint(
            model_name='gymclass',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='gym_class_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['gym_class', 'start_time'], name='gym_classes_gym_cla_4276e1_idx'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['organization', 'start_time'], name='gym_classes_organiz_157b76_idx'),
        ),
    ]
